plugins { id 'com.android.application' }

android {
    namespace 'com.glon.athlete'
    compileSdk 35

    defaultConfig {
        applicationId "com.glon.athlete"
        minSdk 26
        targetSdk 35
        versionCode 36
        versionName "36"
    }

    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.9.24')
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.webkit:webkit:1.11.0'
}
